const browserSync = require('browser-sync')
const config = require('../../config')
const gulp = require('gulp')
const uglify = require('gulp-uglify')
const sourcemaps = require('gulp-sourcemaps')
const babel = require('gulp-babel')
const path = require('path')
const changed = require('gulp-changed')

// Concat and minfy JS
gulp.task('js', () => {
  gulp.src(path.join(config.neue.scripts.src, '**'))
    .pipe(changed(config.neue.scripts.dest))
    .pipe(sourcemaps.init())
      .pipe(babel())
      .pipe(uglify())
    .pipe(sourcemaps.write('.'))
    .pipe(gulp.dest(config.neue.scripts.dest))
    .pipe(browserSync.stream({match: '**/*.js'}))
})
