# Site settings
title: shubox.io
email: joel@shubox.io
shuboxScriptId: "03457406"
smallChatId: "123"
production: "false"
baseurl: ""
url: "https://shubox.io"
description: >
  The easiest and fastest way for your web-app to
  upload images directly to Amazon S3

# Analytics settings
fb_pixel: "1490231254348649"
ga: "UA-80905075-3"

# Site-wide defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: /blog/:year/:month/:day/:title/

# Build settings
markdown: kramdown

plugins:
  - jekyll-feed
  - jekyll-sitemap

exclude:
  - bin

# Collections
collections:
  - examples
  - docs
